# Generated by Django 5.2.17 on 2026-08-23 14:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KiteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('request_token', models.CharField(blank=True, max_length=256)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=8)),
                ('symbol', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('average_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exchange', 'symbol'), name='uniq_holding_symbol')],
            },
        ),
        migrations.CreateModel(
            name='TradeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_row', models.PositiveIntegerField()),
                ('symbol', models.CharField(max_length=32)),
                ('exchange', models.CharField(default='NSE', max_length=8)),
                ('recommended_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('remaining_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('buy_low', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('buy_high', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('target', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('stop_loss', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partial'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('closed_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('closed_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_ltp', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('holding_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('holding_avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'symbol'],
                'constraints': [models.UniqueConstraint(fields=('exchange', 'symbol', 'sheet_row'), name='uniq_trade_sheet_row')],
            },
        ),
        migrations.CreateModel(
            name='CloseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_events', to='trades.tradeidea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('UNDERWEIGHT_BUY_ZONE', 'Underweight in buy zone'), ('TARGET', 'Target hit'), ('STOP_LOSS', 'Stop loss hit')], max_length=32)),
                ('trading_date', models.DateField()),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trades.tradeidea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trade', 'alert_type', 'trading_date'), name='uniq_alert_per_day')],
            },
        ),
    ]
