# Generated by Django 5.2.17 on 2026-08-31 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=64)),
                ('telegram_alerts_enabled', models.BooleanField(default=True)),
                ('google_spreadsheet_id', models.CharField(blank=True, max_length=128)),
                ('google_worksheet', models.CharField(blank=True, default='Aug24-27', max_length=128)),
                ('column_map', models.JSONField(blank=True, default=dict)),
                ('summary_map', models.JSONField(blank=True, default=dict)),
                ('last_sheet_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_zerodha_sync_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App settings',
            },
        ),
        migrations.CreateModel(
            name='KiteFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('exchange', models.CharField(default='NSE', max_length=8)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('side', models.CharField(blank=True, max_length=8)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-filled_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='tradeidea',
            name='opened_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
