# Generated by Django 5.2.17 on 2026-09-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_appsettings_kitfill_opened_on'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradeidea',
            name='uniq_trade_sheet_row',
        ),
        migrations.AddField(
            model_name='tradeidea',
            name='sheet_slug',
            field=models.CharField(db_index=True, default='aug24-27', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='tradeidea',
            constraint=models.UniqueConstraint(fields=('sheet_slug', 'exchange', 'symbol', 'sheet_row'), name='uniq_trade_per_sheet_row'),
        ),
    ]
