# Generated by Django 5.2.17 on 2026-09-01 17:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_sheet_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradebookFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=128, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('isin', models.CharField(blank=True, max_length=16)),
                ('exchange', models.CharField(default='NSE', max_length=8)),
                ('segment', models.CharField(blank=True, max_length=8)),
                ('series', models.CharField(blank=True, max_length=8)),
                ('side', models.CharField(max_length=8)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('trade_date', models.DateField()),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('trade_id', models.CharField(blank=True, max_length=64)),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('auction', models.BooleanField(default=False)),
                ('source_sheet', models.CharField(blank=True, max_length=128)),
                ('tracked', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['filled_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='closeevent',
            name='fill_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='closeevent',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('tradebook', 'Tradebook')], default='manual', max_length=16),
        ),
    ]
